### ISSUE TITLE
ToFileName() is over configuring the file names

### ISSUE THREAD

**Issue by diego-fu-hs** [go-openapi/swag#12]
This is referring to the fix in https://github.com/go-openapi/swag/pull/11

The function will convert all consecutive upper cases to the first letter being upper and rest lower case.  (Example: OAI -> Oai, BY->By).

This creates a problem for any single letter word (`I` and `a`). `AmIAValidRequest` will be converted to `AmIamvalidRequest` and create a file with name `am_iamvalid_request.go`. This is really over configuring the desired behaviour and created a lot of inconsistent with all the other name converting functions:
- `ToCommandName()`
- `ToHumanNameLower()`
- `ToHumanNameTitlte()`
- `ToJSONName()`
- `ToVarName()`
- `ToGoName()`

I purpose to only conserve the values in `commonInitialisms` like all other function, and allow users to pass any custom initialisms if they want additional configurations.

**Comment by fredbi** [comment]
Hello.

I authored this fix for #11 as I was dissatisfied by the handling of file names which
were generated by anonymous types (e.g. OAI someting).
There was another pending issue around the same lines.

The unit test provide examplifies pretty much how the naming convention works.
I actually does a pretty good job, EXCEPT the case for upper-cased, single letter word.

Indeed single letter capitalized words such a "I" or "A" do still pose a problem, and I don't think there is a perfect solution for this.

Maybe that could be configured. So we'll have to make some evolution in the go-swagger  and its YAML config file to support that.

So now
I don't know what you mean by "overconfiguring" (only the 'OAI' word has been added to the list of initialisms) 
and
 you didn't make it clear how this behaviour is inconsistent with the other conventions, as constraints are different for each result 

This fix was a modest contribution and I am aware it is not perfect.
If you have a better solution, please post a PR.

Fred

**Comment by diego-fu-hs** [comment]
@fredbi sorry for being a bit unclear.

I think instead of relying on trying to cover for all use cases, allowing uses to define what they want as initialisms might be a simpler solution to this. I've created this PR https://github.com/go-openapi/swag/pull/13. Feel free to give me any feedback
