### ISSUE TITLE
Go modules

### ISSUE THREAD

**Issue by jerome-laforge** [go-openapi/swag#22]
Hello,
Are you plan to use Go modules?
Thx

**Comment by casualjim** [comment]
for this one it's fairly feasible to do. I'm more worried about all the other packages in our orgs.

go modules showed up a few months ago and now impose breaking changes on the entire ecosystem. It's essentially a major refactoring of every import path, alias etc we're using including in the code generator.

I want to see some more adoption of this in the go ecosystem before embarking on this thing.

**Comment by fredbi** [comment]
Closed with #21
