### ISSUE TITLE
Using uint map keys returns error when analyzing YAML openapi V2 document

### ISSUE THREAD

**Issue by nitinmohan87** [go-openapi/swag#36]
I am trying to understand why map key is restricted to `string` or `int` for an openapi V2 document - https://github.com/go-openapi/swag/blob/master/yaml.go#L179

If I try to analyze a document with `uint` as map key, I am getting the following error
```
import "github.com/go-openapi/loads"

func validateSwagger(b []byte) error {
  _, err := loads.Analyzed(json.RawMessage(b), "")
  return err
}

# error
invalid swagger: analyzed: types don't match expect map key string or int got: uint64
```
Here is the swagger YAML file I am trying to validate.
```
swagger: "2.0"
info:
  title: ""
  version: ""
host: localhost:80
paths:
  /:
    post:
      tags:
      - test service
      summary: test endpoint test service
      operationId: test service#test endpoint
      parameters:
      - name: TestEndpointRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/TestServiceTestEndpointRequestBody'
      responses:
        "200":
          description: OK response.
      schemes:
      - http
definitions:
  TestServiceTestEndpointRequestBody:
    title: TestServiceTestEndpointRequestBody
    type: object
    properties:
      int_map:
        type: object
        example:
          6168161092050465198: Minus explicabo nemo.   <<<< uint map key
        additionalProperties: true
      uint_map:
        type: object
        example:
          2850694428022055785: Aspernatur quo error explicabo pariatur.   <<<< uint map key
        additionalProperties: true
```
The online swagger editor does not complain about the `uint` key type. So I assume using `uint` as map keys must be valid?

**Comment by casualjim** [comment]
it's an oversight. Feel free to submit a PR with a fix.
I have to make a release again very soon because of a regression that was introduced

**Comment by nitinmohan87** [comment]
I have a PR to fix this issue. I am not quite sure how to come up with a unit test in `yaml_test.go`. I can't get `BytesToYAMLDoc` to read `uints` (they always get parsed as ints). I appreciate some help on adding a unit test for this fix.
