### ISSUE TITLE
Why not Uint16Value func?

### ISSUE THREAD

**Issue by sosiska** [go-openapi/swag#42]
Here must be Uint16Value func, why not? I need it.

https://github.com/go-openapi/swag/blob/master/convert_types.go#L360

**Comment by casualjim** [comment]
just an oversight, please send a PR :)

**Comment by sosiska** [comment]
Okey, I can do this

**Comment by sosiska** [comment]
> just an oversight, please send a PR :)

Here you are: https://github.com/go-openapi/swag/pull/43
