### ISSUE TITLE
loadHTTPBytes fails when path requires authentication and/or custom headers

### ISSUE THREAD

**Issue by davidalpert** [go-openapi/swag#44]
I am trying to use the `go-swagger` library to generate a golang client library for a swagger document which is protected and requires:
- a basic auth header
- a custom header

My `swagger generate client` command is failing with this error
```
could not access document at %q [%s]
```
Which I have traced to this `swag` package
- https://github.com/go-openapi/swag/blob/v0.19.8/loading.go#L57-L62

I think I need to extend this `loadHTTPBytes` method with a way to pass in optional authentication mechanism (e.g. basic auth username and password) and a way to decorate the client's headers with custom header key/value pairs, then work backwards to expose that option to the `go-swagger`'s generate commands.

I wonder first if this enhancement to the `loadHTTPBytes` method makes sense and, if so, is there a recommended pattern for passing configuration to the `http.Client{}` struct created to load the swagger doc from a remote URL?

**Comment by casualjim** [comment]
yeah I'm in favor of the enhancement.
I think you can follow the same process and export a global variable which you can set from a cli flag later on.

**Comment by davidalpert** [comment]
great, let me see what I can do.

**Comment by davidalpert** [comment]
whew. took a few tries to get the automated checks all ✅ but I appreciate the attention to detail.

PR #45 is ready for review, and additional feedback is always welcome.
