### ISSUE TITLE
Add Notice file to complete the Apache-2.0 requirements

### ISSUE THREAD

**Issue by Shnitzelil** [go-openapi/swag#62]
Hi,

Our legal department require us to point to Notice file in this repository.
Could you please add simple one.

Best Regards

**Comment by fredbi** [comment]
My position regarding this question can also be seen at:
https://github.com/go-openapi/spec/issues/155#issuecomment-1833618863

**Comment by fredbi** [comment]
Adding a NOTICE is not a requirement. Besides, it has a viral effect and propagates to consumers.
Not about to that unless a more compelling argument is provided. Closing.
