### ISSUE TITLE
Coverity scan - [Security] - Unsafe basic authentication

### ISSUE THREAD

**Issue by raghvendra-dixit** [go-openapi/swag#64]
File : https://github.com/go-openapi/swag/blob/master/loading.go
Details: Basic authentication exposes user credentials in the HTTP header and prevents token rotation. Additionally, many modern browsers cache and automatically submit Basic Authentication credentials creating opportunities for client-side exposure and cross-site request forgery attacks.In github.​com/go-openapi/swag.​loadHTTPBytes.​anonymous%0(string): The application uses the HTTP Basic Authentication scheme.
Screenshot:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/93790023/182474599-2a04ea7e-29c4-4b0c-ba61-e056e3b44c98.png">

**Comment by youyuanwu** [comment]
This is a library that supports basic auth in the loading functionalities.
If you think this is unsafe, then do not use this functionality in this library.

The coverity is complaining about https://pkg.go.dev/net/http#Request.SetBasicAuth std library function that is unsafe. 
You should open an issue with the std lib in golang repo. If golang determines that SetBasicAuth should not be used, we will remove it here in openapi.
